include: package:lint/strict.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

# If necessary, use (ignore: lint) and (ignore_for_file: lint)
linter:
  rules:

    # Personal preference.
    require_trailing_commas: false

    # todo: migrate it
    # In build method don't correct
    no_leading_underscores_for_local_identifiers: false

    # conflicts with `prefer_relative_imports`
    always_use_package_imports: false

    # Personal preference.
    prefer_if_elements_to_conditional_expressions: false

    # Personal preference.
    sort_pub_dependencies: false

    # Sometimes the api of packages can change along with the default value.
    # It can be hard to keep track of.
    avoid_redundant_argument_values: false

    # ====================true

    # I prefer to explicitly specify which asynchronous functions not to expect
    # (use unawaited from dart:async)
    discarded_futures: true
    unawaited_futures: true
