include: package:lint/analysis_options.yaml

#analyzer:
#  exclude:
#  - '**.freezed.dart'

# Not happy with the default? Customize the rules depending on your needs.
# Here are some examples:
linter:
  errors:
    unused_field: ignore
  #    unused_local_variable: ignore

  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true

    sort_pub_dependencies: false

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    public_member_api_docs: false #true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Back to the 80s
    lines_longer_than_80_chars: false

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    prefer_if_elements_to_conditional_expressions: false
    unawaited_futures: true

    avoid_positional_boolean_parameters: false

    no_leading_underscores_for_local_identifiers: false

    require_trailing_commas: false

    always_use_package_imports: false

    use_super_parameters: false


