targets:
  $default:
    builders:
      auto_route_generator:autoRouteGenerator:
        enabled: true
      #        generate_for:
      #          include:
      #            - lib/utils/routes/routes.dart
      json_serializable:json_serializable:
        enabled: false
        generate_for:
          include:
            - lib/**/models/**/*.dart
      freezed:
        enabled: true
#        generate_for:
#          - '**/models/**/*.dart'
#          - '**/models/*.dart'
#          - '**/search_body_state.dart'