targets:
  $default:
    builders:
    # not to be confused with
    # auto_route_generator:auto_route_generator
      auto_route_generator:auto_router_generator:
        enabled: true
        generate_for:
            - lib/utils/routes/routes.dart
      json_serializable:json_serializable:
        enabled: true
        generate_for:
            - lib/**/models/**.dart
      freezed:
        enabled: true
        generate_for:
            - lib/**/models/**.dart
            - lib/**/search_body_state.dart