name: weather_today
description: Weather for every day.
publish_to: none

version: 3.3.0-pre.3+16

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # service weather
  weather_pack: ^1.0.0

  # Widgets
  material_floating_search_bar_2: ^0.5.0
  expandable: ^5.0.1
  smooth_page_indicator: ^1.1.0
  country_icons: ^2.0.2
  fluttertoast: ^8.2.2
  fl_chart: ^0.63.0
  weather_animation: ^0.0.2
  sliver_tools: ^0.2.12

  # Theme
  flex_color_scheme: ^7.3.1

  # Models and annotation
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Routing
  auto_route: ^7.8.3
  dismissible_page: ^1.0.2
#  dismissible_page:
#    git:
#      url: https://github.com/Tkko/Flutter_dismissible_page
#      ref: master

  # Database
  shared_preferences: ^2.2.1
  cardoteka:
    path: ../../cardoteka

  # State manager
  hooks_riverpod: ^2.4.0
  flutter_hooks: 0.20.1

  # Localization
  slang: ^3.23.0
  slang_flutter: ^3.23.0
  flutter_localizations:
    sdk: flutter

  # Utility
  intl: ^0.18.1
  loggy: ^2.0.3
  stack_trace: ^1.11.0 # after bump [flutter_test] sdk
  url_launcher: ^6.1.14
  meta: ^1.9.1 # after bump [flutter_test] sdk
  package_info_plus: ^4.1.0
  flutter_markdown: ^0.6.17+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  icons_launcher: ^2.1.3
  freezed: ^2.4.2

  # linters
  custom_lint: ^0.5.3
  riverpod_lint: ^2.1.0
  lint: ^2.1.2

flutter:

  uses-material-design: true

  # https://flutter.dev/assets-and-images
  assets:
    - assets/icons/
    - assets/images/
    - assets/weather_icons/
    - assets/images/attribution/owm/
    - assets/doc/

  fonts:
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Anonymous Pro
      fonts:
        - asset: assets/fonts/Anonymous_Pro/AnonymousPro-Regular.ttf
        - asset: assets/fonts/Anonymous_Pro/AnonymousPro-Italic.ttf
          style: italic

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf

    - family: Marck Script
      fonts:
        - asset: assets/fonts/Marck_Script/MarckScript-Regular.ttf

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Italic.ttf
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic

    - family: Neucha
      fonts:
        - asset: assets/fonts/Neucha/Neucha-Regular.ttf

    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Medium.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic.ttf
          style: italic

    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/Noto_Sans_Mono/NotoSansMono-Regular.ttf

    - family: Noto Serif
      fonts:
        - asset: assets/fonts/Noto_Serif/NotoSerif-Regular.ttf
        - asset: assets/fonts/Noto_Serif/NotoSerif-Italic.ttf
          style: italic

    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
