name: weather_today
description: Weather for every day.
publish_to: none

version: 3.1.1+5

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # service weather
  weather_pack: ^0.0.2

  # Widgets
  material_floating_search_bar: ^0.3.7
  expandable: ^5.0.1
  smooth_page_indicator: ^1.0.0+2
  country_icons: ^2.0.2
  fluttertoast: ^8.1.2
  fl_chart: ^0.55.2
  weather_animation: ^0.0.2

  # Theme
  flex_color_scheme: ^6.1.2

  # Models and annotation
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

  # Routing
  auto_route: ^5.0.4

  # Database
  shared_preferences: ^2.0.15

  # State manager
  hooks_riverpod: ^2.1.3
  flutter_hooks: 0.18.5+1

  # Localization
  slang: ^3.7.0
  slang_flutter: ^3.7.0
  flutter_localizations:
    sdk: flutter

  # Utility
  intl: ^0.17.0 # after bump flutter
  loggy: ^2.0.3
  stack_trace: ^1.10.0 # after bump flutter
  url_launcher: ^6.1.7
  meta: ^1.8.0
  package_info_plus: ^3.0.2
  flutter_markdown: ^0.6.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  icons_launcher: ^2.0.6 # after bump flutter
  freezed: ^2.3.2
  lint: ^2.0.1


flutter:

  uses-material-design: true

  # https://flutter.dev/assets-and-images
  assets:
    - assets/icons/icon.png
    - assets/images/
    - assets/images/attribution/owm/
    - assets/doc/

  fonts:
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Anonymous Pro
      fonts:
        - asset: assets/fonts/Anonymous_Pro/AnonymousPro-Regular.ttf
        - asset: assets/fonts/Anonymous_Pro/AnonymousPro-Italic.ttf
          style: italic

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf

    - family: Marck Script
      fonts:
        - asset: assets/fonts/Marck_Script/MarckScript-Regular.ttf

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Italic.ttf
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic

    - family: Neucha
      fonts:
        - asset: assets/fonts/Neucha/Neucha-Regular.ttf

    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Medium.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic.ttf
          style: italic

    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/Noto_Sans_Mono/NotoSansMono-Regular.ttf

    - family: Noto Serif
      fonts:
        - asset: assets/fonts/Noto_Serif/NotoSerif-Regular.ttf
        - asset: assets/fonts/Noto_Serif/NotoSerif-Italic.ttf
          style: italic

    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
