name: weather_today
description: Weather for every day.
publish_to: none

version: 3.3.1+21

environment:
  sdk: ^3.0.0

dependency_overrides:
  meta: ^1.15.0
  web: ^1.0.0

dependencies:
  flutter:
    sdk: flutter

  # service weather
  weather_pack: ^1.1.0

  # Widgets
  material_floating_search_bar_2: ^0.5.0
  expandable: ^5.0.1
  smooth_page_indicator: ^1.2.0
  country_icons: ^3.0.0
  fluttertoast: ^8.2.6
  # coldfix: this error was fixed in version 0.64
  # https://github.com/imaNNeo/fl_chart/issues/1388
  # causing my hourly temperature graphs to stop showing negative temps correctly
  fl_chart: 0.63.0
  weather_animation: ^1.0.1
  sliver_tools: ^0.2.12

  # Theme
  flex_color_scheme: ^7.3.1
  flex_color_picker: ^3.3.0

  # Models and annotation
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Routing
  auto_route: ^9.1.0
  dismissible_page: ^1.0.2
#  dismissible_page:
#    git:
#      url: https://github.com/Tkko/Flutter_dismissible_page
#      ref: master

  # Database
  shared_preferences: ^2.2.3
  cardoteka: ^1.0.1

  # State manager
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5

  # Localization
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  flutter_localizations:
    sdk: flutter

  # Network
  http: any

  # Utility
  intl: ^0.19.0
  loggy: ^2.0.3
  stack_trace: ^1.11.1
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

  # todo: when don't resolve https://github.com/flutter/flutter/issues/107073
#  flutter_markdown: ^0.6.18
  flutter_markdown_selectionarea: ^0.6.17+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  icons_launcher: ^3.0.0-beta.2
  freezed: ^2.5.7

  # linters
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12
  lint: ^2.3.0

flutter:

  uses-material-design: true

  # https://flutter.dev/assets-and-images
  assets:
    - assets/icons/
    - assets/images/
    - assets/weather_icons/
    - assets/images/attribution/owm/
    - assets/images/attribution/open-meteo/
    - assets/doc/

  fonts:
    # see https://flutter.dev/custom-fonts/#from-packages
    - family: Anonymous Pro
      fonts:
        - asset: assets/fonts/Anonymous_Pro/AnonymousPro-Regular.ttf
        - asset: assets/fonts/Anonymous_Pro/AnonymousPro-Italic.ttf
          style: italic

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat/Caveat-Medium.ttf
        - asset: assets/fonts/Caveat/Caveat-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf

    - family: Marck Script
      fonts:
        - asset: assets/fonts/Marck_Script/MarckScript-Regular.ttf

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Italic.ttf
          style: italic

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic

    - family: Neucha
      fonts:
        - asset: assets/fonts/Neucha/Neucha-Regular.ttf

    - family: Noto Sans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Medium.ttf
        - asset: assets/fonts/Noto_Sans/NotoSans-Italic.ttf
          style: italic

    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/Noto_Sans_Mono/NotoSansMono-Regular.ttf

    - family: Noto Serif
      fonts:
        - asset: assets/fonts/Noto_Serif/NotoSerif-Regular.ttf
        - asset: assets/fonts/Noto_Serif/NotoSerif-Italic.ttf
          style: italic

    - family: Open Sans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf

    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald/Oswald-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
